### ISSUE TITLE
Char _ is allowed number separatist

### ISSUE THREAD

**Issue by Alexey-T** [digitalcora/sublime-text-gleam#6]
```
  # Numbers
  number:
    - match: \b0b[01]+\b
      scope: constant.numeric.binary.gleam
    - match: \b0o[0-7]+\b
      scope: constant.numeric.octal.gleam
    - match: \b[[:digit:]][[:digit:]_]*(\.[[:digit:]]*(e-?[[:digit:]]+)?)?\b
      scope: constant.numeric.decimal.gleam
    - match: \b0x[[:xdigit:]]+\b
      scope: constant.numeric.hexadecimal.gleam
```
'_' is valid digit separatist now.
